### ISSUE TITLE
Better performance through some changes

### ISSUE THREAD

**Issue by gettalong** [caiges/Ruby-RC4#12]
Hi,

I had the need for a pure Ruby RC4 implementation and implemented one. Alas, then I found this project.

While testing performance it seems that my implementation is faster. Maybe you can use some parts to adapt yours.

Here is my implementation:

~~~ ruby
class ARC4

  # Creates a new ARC4 object using the given encryption key.
  def initialize(key)
    initialize_state(key)
  end

  # Processes the given data.
  #
  # Since this is a symmetric algorithm, the same method can be used for encryption and
  # decryption.
  def process(data)
    result = data.dup.force_encoding(Encoding::BINARY)
    i = j = di = 0
    while di < result.length
      i = (i + 1) % 256
      j = (j + @state[i]) % 256
      @state[i], @state[j] = @state[j], @state[i]
      result.setbyte(di, result.getbyte(di) ^ @state[(@state[i] + @state[j]) % 256])
      di += 1
    end
    result
  end
  alias :decrypt :process
  alias :encrypt :process

  private

  # The initial state which is then modified by the key-scheduling algorithm
  INITIAL_STATE = (0..255).to_a

  # Performs the key-scheduling algorithm to initialize the state.
  def initialize_state(key)
    i = j = 0
    @state = INITIAL_STATE.dup
    key_length = key.length
    while i < 256
      j = (j + @state[i] + key.getbyte(i % key_length)) % 256
      @state[i], @state[j] = @state[j], @state[i]
      i += 1
    end
  end

end
~~~

I think the parts that make it faster are:

* Using `String#getbyte` and `String#setbyte` instead of unpacking and packing the string
* The initialization of the initial state
* Not calling a method (in your case #round) while processing data

**Comment by caiges** [comment]
Nice work! Sorry, I meant to respond to this when you first opened the issue. There are a number of areas where performance could be improved as you have stated. It would be prudent to put your work on a branch as changing the current implementation should be done carefully. I'm open to adding contributors or if you're fine with opening a PR we can go that route too.

**Comment by gettalong** [comment]
Thanks, I have created a pull request (see #13) with the changes applied to the `RC4` class.
